################################################################################
# Site settings                                                                #
################################################################################

title:                Kladde
description:          Dies. Das. Einfach verschiedene Dinge.
lang:                 de_DE
author:               chhch
date_format:          "%d.%m.%Y"

################################################################################
# Default Settings                                                             #
#  for more settings see                                                       #
#  https://jekyllrb.com/docs/configuration/#default-configuration              #
#  https://git.io/v5E3u                                                        #
################################################################################

# Handling Reading
safe:                 true                # cannot changed
exclude:
  - docker
  - Gemfile
  - Gemfile.lock

# Filtering Content
future:               false               # changed

# Plugins, see https://git.io/v5EO0
plugins:
# must explcit be loaded
#  - jekyll-avatar
  - jekyll-feed
#  - jekyll-mentions
#  - jekyll-redirect-from
  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jemoji
# already loaded
#  - jekyll-coffeescript
#  - jekyll-default-layout
#  - jekyll-gist
#  - jekyll-github-metadata
#  - jekyll-optional-front-matter
#  - jekyll-paginate
#  - jekyll-readme-index
#  - jekyll-relative-links
#  - jekyll-titles-from-headings
# only for testing
#  - jekyll-livereload

gist:
  noscript:           false               # cannot changed

# Conversion
markdown:             kramdown            # cannot changed
highlighter:          rouge               # cannot changed
lsi:                  false               # cannot changed
incremental:          false               # cannot changed

# Outputting
permalink:            pretty

# Theme
theme:                jekyll-theme-primer # can changed

# Markdown Processors
kramdown:
  template:           ""                  # cannot changed
  math_engine:        mathjax             # cannot changed
  syntax_highlighter: rouge               # cannot changed
  input:              GFM                 # can changed
  hard_wrap:          false               # can changed
  gfm_quirks:         paragraph_end       # can changed
