version: "3.3"
services:
  jekyll_site:
    container_name: jekyll
    image: jekyll/jekyll:3.5.2
    command: bash -c "bundle update && bundle exec jekyll serve --drafts"
    volumes:
      - type: bind
        source: ..
        target: /srv/jekyll
    ports:
      - published: 4000
        target: 4000
